image:
  repository: gilesknap/gphotos-sync
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

cronjob:
  schedule: "0 2 * * 1"

persistence:
  enabled: true
  existingClaim: googlephotobackuppvc